# bomber_embed_binary(<input> <output.cpp> <symbol>)
#
# Compiles a binary file INTO the executable as a byte array, so the shipped
# OPEN-BM95.exe stays a single self-contained file the user drops into their
# install folder — the same property apps/game/app.rc gives the window icon,
# but portable: an .rc only exists on Windows, and libs/game builds on the
# linux/macos/headless presets too.
#
# Emits `extern const unsigned char <symbol>[]` + `extern const unsigned int
# <symbol>_size` in namespace bomber::game. Runs at CONFIGURE time and adds the
# input to CMAKE_CONFIGURE_DEPENDS, so replacing the asset re-generates the
# source on the next build without a manual step.
function(bomber_embed_binary input output symbol)
  file(READ "${input}" hex HEX)
  # "0a1b2c" -> "0x0a,0x1b,0x2c," with a newline every 16 bytes so the generated
  # file stays diffable and no compiler hits a line-length limit.
  string(REGEX REPLACE "(................................)" "\\1\n" hex "${hex}")
  string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," body "${hex}")
  file(SIZE "${input}" size)
  file(GENERATE OUTPUT "${output}" CONTENT
"// GENERATED by cmake/EmbedBinary.cmake from ${input} -- do not edit.
namespace bomber::game {
extern const unsigned char ${symbol}[] = {
${body}
};
extern const unsigned int ${symbol}_size = ${size}u;
}  // namespace bomber::game
")
  set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${input}")
endfunction()
